table Dim_Campaign
	lineageTag: b6aae0e9-506d-43ef-afba-7cd66d3e8713

	column 'Kampanj Vecka'
		dataType: int64
		formatString: 0
		lineageTag: 71c88aff-45cf-4eed-838f-465e9135e0ef
		summarizeBy: sum
		sourceColumn: Kampanj Vecka

		annotation SummarizationSetBy = Automatic

	column 'Campaign Week'
		dataType: string
		lineageTag: 02847bf8-b7d9-4d62-b823-0b0df01bb640
		summarizeBy: none
		sourceColumn: Campaign Week

		annotation SummarizationSetBy = Automatic

	column 'Article (EAN-Nr)'
		dataType: int64
		formatString: 0
		lineageTag: 2cd0fde5-4ea2-45e5-800c-a2bc6b7da306
		summarizeBy: none
		sourceColumn: Article (EAN-Nr)

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 94d4a4ee-7af8-49d4-99b8-ff0dc6f7442f
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: bf03450c-99d7-4f37-a1b7-37bfe8469565
			defaultHierarchy: LocalDateTable_5c791ee3-9abc-4f98-ba0b-ac466afe8486.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column EndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 3dc90874-af98-4d59-b705-ada88a68ea6c
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: 90d32b16-42c6-46ad-850e-352fa87ee095
			defaultHierarchy: LocalDateTable_192b99cc-5dbf-4610-838f-55374349c35e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Discount(%)
		dataType: double
		lineageTag: 13195c2f-9780-4a74-8f67-a4085d122adc
		summarizeBy: sum
		sourceColumn: Discount(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: fab19ae5-0f4f-4511-b974-b0e241d1ecde
		summarizeBy: count
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	partition Dim_Campaign = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(campaignUrl), null, true),
				    Kampanj_Sheet = Source{[Item="Kampanj",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Kampanj_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Kampanj ID", type text}, {"Kampanj Namn", type text}, {"Vara (EAN-Nr)", Int64.Type}, {"StartDatum", type any}, {"SlutDatum", type any}, {"Discount(%)", type number}}),
				    #"Changed startdatum till swe" = Table.TransformColumnTypes(#"Changed Type", {{"StartDatum", type date}}, "sv-SE"),
				    #"Changed slutdatum till swe" = Table.TransformColumnTypes(#"Changed startdatum till swe", {{"SlutDatum", type date}}, "sv-SE"),
				    #"Merged Queries" = Table.NestedJoin(#"Changed slutdatum till swe", {"Vara (EAN-Nr)"}, Dim_Product, {"Product EAN/PLU"}, "Dim_Product", JoinKind.LeftOuter),
				    #"Expanded Dim_Product" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Product", {"Produkt ID"}, {"Dim_Product.Produkt ID"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim_Product","K","",Replacer.ReplaceText,{"Kampanj ID"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Kampanj ID", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Kampanj ID", "Kampanj Vecka"}, {"Dim_Product.Produkt ID", "Product ID"}, {"Kampanj Namn", "Campaign Week"}, {"SlutDatum", "EndDate"}, {"StartDatum", "StartDate"}, {"Vara (EAN-Nr)", "Article (EAN-Nr)"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

