table Fact_TimeReports
	lineageTag: 69624a9a-ea77-440d-87f7-ee50c859c52e

	column 'Source.Name'
		dataType: string
		isHidden
		lineageTag: e788e679-ca2b-43a3-b99a-2cc6f403b6bc
		summarizeBy: none
		sourceColumn: Source.Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: f3d596af-2f6a-4cef-ac44-7806d995d71b
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column SweMonth
		dataType: string
		lineageTag: dcd6113e-1e94-43b3-95f4-7d2830514db6
		summarizeBy: none
		sourceColumn: SweMonth
		sortByColumn: MonthNumber

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Hours
		dataType: int64
		formatString: 0
		lineageTag: a6f34718-d29e-41bf-a2c0-3ac91f4516a6
		summarizeBy: sum
		sourceColumn: Hours

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 90591def-f09c-4910-890b-1b2aff12c0ce
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Working hours/Vacation'
		dataType: string
		lineageTag: 485cb89f-9db9-4d46-9805-c672081d5b42
		summarizeBy: none
		sourceColumn: Working hours/Vacation

		annotation SummarizationSetBy = Automatic

	column EngSweMånad
		dataType: string
		isHidden
		lineageTag: 6425953c-0744-4f16-ac36-6fb25435c29d
		summarizeBy: none
		sourceColumn: EngSweMånad
		sortByColumn: MonthNumber

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 0aa80027-b4af-4365-9bb0-9ed1407e2ef6
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthlySalary
		dataType: double
		formatString: #,0.00\ "kr";-#,0.00\ "kr";#,0.00\ "kr"
		lineageTag: 0c203d6a-ef5e-49c4-86cc-3e5aa74804ed
		summarizeBy: sum
		sourceColumn: MonthlySalary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"sv-SE"}

	column 'Monthly Salary Without Overtime'
		dataType: double
		lineageTag: b0afc65b-56a9-4f80-bfa4-e6233451a12a
		summarizeBy: sum
		sourceColumn: Monthly Salary Without Overtime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5cbb700c-ce34-435e-ae30-4d3e3d99c149
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Dim_Personnel.Fixed salary'
		dataType: int64
		formatString: 0
		lineageTag: 0ce8efba-cf8e-4345-89cc-996ca3924fa7
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Fixed salary

		annotation SummarizationSetBy = Automatic

	column 'Dim_Personnel.Overtime compensation/hour'
		dataType: double
		lineageTag: 997557bb-0b39-4a07-bd3b-44c587c34b1e
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Overtime compensation/hour

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dim_Personnel.Normal working hours'
		dataType: int64
		formatString: 0
		lineageTag: 97daf289-637b-4bf6-b6de-e1e8ef2b383e
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Normal working hours

		annotation SummarizationSetBy = Automatic

	column 'Dim_Personnel.Employer''s contribution on fixed salary'
		dataType: double
		lineageTag: ebdeff56-ad25-42df-a41a-b02d699959f4
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Employer's contribution on fixed salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dim_Personnel.Employer Contribution (%)'
		dataType: double
		lineageTag: 6471d1a8-6668-43f2-a075-7f50c828cef9
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Employer Contribution (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dim_Personnel.Pension (%)'
		dataType: int64
		formatString: 0
		lineageTag: c36ca6b8-e814-4939-9d4b-2fdcee7958e7
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Pension (%)

		annotation SummarizationSetBy = Automatic

	column 'Dim_Personnel.Vacation Pay Hourly Employees (%)'
		dataType: int64
		formatString: 0
		lineageTag: d7edf3da-1cda-40a4-89ba-efdfa8aa2f86
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Vacation Pay Hourly Employees (%)

		annotation SummarizationSetBy = Automatic

	column 'Dim_Personnel.Hourly wage'
		dataType: int64
		formatString: 0
		lineageTag: 24b74918-6951-4944-9e3f-07265bb3c1b8
		summarizeBy: sum
		sourceColumn: Dim_Personnel.Hourly wage

		annotation SummarizationSetBy = Automatic

	partition Fact_TimeReports = m
		mode: import
		source = ```
				let
				    Source = SharePoint.Files(urlSharepoint, [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Extension] = ".xlsx") and ([Name] = "HR_2023-02-24.xlsx")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"AnstID", Int64.Type}, {"Månad", type text}, {"Timmar", Int64.Type}, {"År", Int64.Type}, {"Action", type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type",{{"Action", "Arbetstid/Semester"},{"Månad", "SweMånad"}}),
				    #"Added Conditional EngMonth" = Table.AddColumn(#"Renamed Columns2", "EngSweMånad", each if [SweMånad] = "Januari" then "January" else if [SweMånad] = "Februari" then "February" else if [SweMånad] = "Mars" then "March" else if [SweMånad] = "Maj" then "May" else if [SweMånad] = "Juni" then "June" else if [SweMånad] = "Juli" then "July" else if [SweMånad] = "Augusti" then "August" else if [SweMånad] = "Oktober" then "October" else [SweMånad]),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Conditional EngMonth", "Custom", each if [EngSweMånad] = "January" then 1 else if [EngSweMånad] = "February" then 2 else if [EngSweMånad] = "March" then 3 else if [EngSweMånad] = "April" then 4 else if [EngSweMånad] = "May" then 5 else if [EngSweMånad] = "June" then 6 else if [EngSweMånad] = "July" then 7 else if [EngSweMånad] = "August" then 8 else if [EngSweMånad] = "September" then 9 else if [EngSweMånad] = "October" then 10 else if [EngSweMånad] = "November" then 11 else if [EngSweMånad] = "December" then 12 else 0),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "MånadsNummer"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"MånadsNummer", Int64.Type}, {"EngSweMånad", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"AnstID"}, Dim_Personnel, {"AnstID"}, "Dim_Personnel", JoinKind.LeftOuter),
				    #"Expanded Dim_Personnel" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Personnel", {"Fixed Salary", "Overtime compensation/hour", "Normalworkinghours", "Arbetsgivaravgift på fast lön", "Arbetsgivaravgift (%)", "Pension (%)", "Holiday pay for hourly employees (%)", "Hourly Rate"}, {"Dim_Personnel.Fast lön", "Dim_Personnel.Övertidsersättning/h", "Dim_Personnel.Normalarbetstid", "Dim_Personnel.Arbetsgivaravgift på fast lön", "Dim_Personnel.Arbetsgivaravgift (%)", "Dim_Personnel.Pension (%)", "Dim_Personnel.Semestererättning timanställda (%)", "Dim_Personnel.Timlön"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Dim_Personnel", "Månadslön", each if [Timmar] > [Dim_Personnel.Normalarbetstid] *4 and [Dim_Personnel.Timlön] = null
				
				then 
				([Timmar]-[Dim_Personnel.Normalarbetstid] *4
				) * [#"Dim_Personnel.Övertidsersättning/h"] + [Dim_Personnel.Fast lön]
				
				else if 
				[Dim_Personnel.Timlön] = null
				then [Dim_Personnel.Fast lön]
				
				else 
				[Timmar] * [Dim_Personnel.Timlön]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Månadslön", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "Custom", each if 
				[Dim_Personnel.Timlön] = null
				then [Dim_Personnel.Fast lön]
				
				else 
				[Timmar] * [Dim_Personnel.Timlön]),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Custom1",{{"Custom", "Månadslön utan övertid"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Månadslön utan övertid", type number}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type3", "SweMånad", "SweMånad - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "År", "År - Copy"),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"År - Copy", type text}}, "en-US"),{"SweMånad - Copy", "År - Copy"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Merged"),
				    #"Renamed Columns4" = Table.RenameColumns(#"Merged Columns",{{"Merged", "Date"}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Renamed Columns4", {{"Date", type date}}, "sv-SE"),
				    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type with Locale",{{"Dim_Personnel.Pension (%)", "Dim_Personnel.Pension (%)"}, {"Månadslön utan övertid", "Monthly Salary Without Overtime"}, {"Månadslön", "MonthlySalary"}, {"Dim_Personnel.Arbetsgivaravgift (%)", "Dim_Personnel.Employer Contribution (%)"}, {"Dim_Personnel.Semestererättning timanställda (%)", "Dim_Personnel.Vacation Pay Hourly Employees (%)"}, {"AnstID", "EmployeeID"}, {"År", "Year"}, {"Arbetstid/Semester", "Working hours/Vacation"}, {"Dim_Personnel.Arbetsgivaravgift på fast lön", "Dim_Personnel.Employer's contribution on fixed salary"}, {"Dim_Personnel.Fast lön", "Dim_Personnel.Fixed salary"}, {"Dim_Personnel.Normalarbetstid", "Dim_Personnel.Normal working hours"}, {"Dim_Personnel.Övertidsersättning/h", "Dim_Personnel.Overtime compensation/hour"}, {"Dim_Personnel.Timlön", "Dim_Personnel.Hourly wage"}, {"MånadsNummer", "MonthNumber"}, {"SweMånad", "SweMonth"}, {"Timmar", "Hours"}})
				in
				    #"Renamed Columns5"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

